server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_product_service
    username: root
    password: Basketball

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true

  application:
    name: product-service

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

project:
  image: productService/src/main/resources/static/
