server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_user_service
    username: root
    password: Basketball

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true

  application:
    name: user-service

