server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_order_service
    username: root
    password: Basketball

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
    show-sql: true

  application:
    name: order-service

  mail:
    host: smtp.gmail.com
    username: gelbuhherpa456@gmail.com
    password: myhlafudrncsbogo
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

